/**
 * @description This is a test class for TAG_ContactFormSendEmail
 *
 * @author Andre Colle <andre.colle@nav.no>
 * @since 2023-11-14 Created.
 *
 * @see [License](https://github.com/navikt/crm-arbeidsgiver-kontaktskjema/blob/main/LICENSE)
 * @see [Github](https://github.com/navikt/crm-arbeidsgiver-kontaktskjema)
 * @see TAG_ContactFormSendEmail
 *
 * @group TAG Contact Form
 */
@IsTest
public with sharing class TAG_ContactFormSendEmail_Test {
 
}
