/**
 * @description This Contact Form Send Email class sends email receipts to users who submitted the kontaktskjema experience site.
 *
 * @author Andre Colle <andre.colle@nav.no>
 * @since 2023-11-14 Created.
 *
 * @see [License](https://github.com/navikt/crm-arbeidsgiver-kontaktskjema/blob/main/LICENSE)
 * @see [Github](https://github.com/navikt/crm-arbeidsgiver-kontaktskjema)
 * @see TAG_ContactFormController
 * @see TAG_ContactFormSendEmail_Test
 *
 * @group TAG Contact Form
 */
public with sharing class TAG_ContactFormSendEmail {    
}