/**
 * @description This is a test class for TAG_ContactFormSendEmail
 *
 * @author Andre Colle <andre.colle@nav.no>
 * @since 2023-11-14 Created.
 *
 * @see [License](https://github.com/navikt/crm-arbeidsgiver-kontakt-oss/blob/main/LICENSE)
 * @see [Github](https://github.com/navikt/crm-arbeidsgiver-kontakt-oss)
 * @see TAG_ContactFormSendEmail
 *
 * @group TAG Contact Form
 */
public with sharing class TAG_ContactFormSendEmail_Test {
    public TAG_ContactFormSendEmail_Test() {

    }
}